package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"
	"younified-backend/contracts/cms/model"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// CreateBlogPost is the resolver for the createBlogPost field.
func (r *mutationResolver) CreateBlogPost(ctx context.Context, unionID primitive.ObjectID, input model.Blog, images []*string) (*model.Blog, error) {
	return r.CMSController.CreateBlogPost(ctx, unionID, input, images)
}

// DeleteBlogPost is the resolver for the deleteBlogPost field.
func (r *mutationResolver) DeleteBlogPost(ctx context.Context, unionID primitive.ObjectID, blogID primitive.ObjectID) (*string, error) {
	return r.CMSController.DeleteBlogPost(ctx, unionID, blogID)
}

// MakeFeature is the resolver for the makeFeature field.
func (r *mutationResolver) MakeFeaturedBlog(ctx context.Context, unionID primitive.ObjectID, blogID primitive.ObjectID, featured bool) (*string, error) {
	return r.CMSController.FeatureBlogPost(ctx, unionID, blogID, featured)
}

// EditBlogPost is the resolver for the editBlogPost field.
func (r *mutationResolver) UpdateBlogPost(ctx context.Context, unionID primitive.ObjectID, blogID primitive.ObjectID, input model.Blog) (*model.Blog, error) {
	return r.CMSController.UpdateBlogPost(ctx, unionID, blogID, input)
}

// GetBlogPosts is the resolver for the getBlogPosts field.
func (r *queryResolver) GetBlogPosts(ctx context.Context) ([]*model.Blog, error) {
	return r.CMSController.GetBlogPosts(ctx)
}

// GetOneBlogPost is the resolver for the getOneBlogPost field.
func (r *queryResolver) GetOneBlogPost(ctx context.Context, blogID primitive.ObjectID) (*model.Blog, error) {
	return r.CMSController.GetOneBlogPost(ctx, blogID)
}
