package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"younified-backend/contracts/communication/model"
)

// SendMail is the resolver for the SendMail field.
func (r *mutationResolver) SendMail(ctx context.Context, input model.SendMail) (string, error) {
	return r.CommsController.SendMail(ctx, input)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
